jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik5vdXIgVG9sYmEiLCJpYXQiOjE1MTYyMzkwMjJ9.1GlqZF3omTnaE7v9hCEHC_rO5TqUDg00vHTlr-IgqRY
  access-token-expiration: 900000  # 15 minutes in milliseconds
  refresh-token-expiration: 86400000  # 24 hours in milliseconds
spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID  # Replace with actual client ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET  # Replace with actual secret
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            client-id: YOUR_GITHUB_CLIENT_ID  # Replace with actual client ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET  # Replace with actual secret
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ns9121212@gmail.com
    password: zmpe cdog bvrn vdve
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/moviesdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Nour@1205
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ns9121212@gmail.com
    password: zmpe cdog bvrn vdve
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true